apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://charts.gitlab.io/'
      chart: gitlab
      targetRevision: 8.*
      helm:
        valueFiles:
          - $values/helm/lab.values.yaml
    - repoURL: 'https://github.com/qcserestipy/gitlab-helm.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
