apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-scale-set-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'ghcr.io/actions/actions-runner-controller-charts'
      chart: gha-runner-scale-set-controller
      targetRevision: 0.10.1
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
